# agents/manager.py

import os
from dotenv import load_dotenv
from crewai import Agent, LLM



def create_manager_agent(gemini_model):


    manager_agent = Agent(
        role="AI Project Manager",
        goal="\n".join([
            "Efficiently coordinate AI agents to analyze, refactor, and explain code following Clean Code principles.",
            "Ensure that outputs are combined into a final structured report including:",
            "1. The original {code}.",
            "2. The refactored version of the code.",
            "3. Clean Code lessons generated by the educator based on the analysis."
            "in the order specified above.",
            "Ensure that the oreder is orginal code, refactored code, and clean code lessons after them.",
        ]),
        backstory="\n".join([
            "You are a seasoned project manager with deep experience in software engineering and clean architecture.",
            "You excel at coordinating teams to produce maintainable and clean code.",
            "You ensure the highest quality standards are met by validating outputs and structuring final reports properly."
        ]),
        llm=gemini_model.get_llm(),

        verbose=False,
        allow_delegation=True
    )

    return manager_agent
